name: Learning To Cache

on: [push]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Create python file  
        run: echo 'print("Hello, World!")' > helloworld.py
      
      - name: Cache helloworld file
        uses: actions/cache@v3
        with:
          path: helloworld.py
          key: helloworld

      - name: See files
        run: ls

  retrieve_cache:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Restore cached helloworld.py
        uses: actions/cache@v3
        with:
          key: helloworld
          path: helloworld.py  # Correctly specify the path to restore

      - name: Retrieve cached file
        run: |
          ls
          python helloworld.py  # Run the file to see output
