name: Learning To Cache
on: [push]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Create python file  
        run: echo 'print("Hello, World!")' > helloworld.py
      - name: Cache helloworld file
        uses: actions/cache@v3
        with:
          path: helloworld.py
          key: helloworld
      - name: see files
        run: ls
  retrieve_cache:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Restore cached math_operator.py
        uses: actions/cache@v2
        with:
          key: helloworld
          path: math.py
      - name: retrieve cached file
        run: ls