name: Math Operator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache math_operator.py
      uses: actions/cache@v2
      with:
        # Using a unique key based on OS and file hash for caching
        key: ${{ runner.os }}-math_operator-${{ hashFiles('math_operator.py') }}
        path: math_operator.py

    - name: Display cached file content
      if: steps.cache.outputs.cache-hit == 'true'
      run: cat math_operator.py

  print-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore cached math_operator.py
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-math_operator-${{ hashFiles('math_operator.py') }}
        path: math_operator.py

    - name: Print cached math_operator.py content
      if: steps.cache.outputs.cache-hit == 'true'
      run: cat math_operator.py
